version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/deepsourcelabs/cli"

[[analyzers]]
name = "secrets"
enabled = true

[[transformers]]
name = "gofumpt"
enabled = true
