name = "Todo comments checker"
path = "@deepsource/demo-python"
description = "Finds the TODO comments in codebase."
# category = "doc"
tags = ["documentation","todo"]
environment_variables = {CODE_PATH = "/code"}

[urls]
 source = "https://github.com/deepsourcelabs/2do-checker"
 documentation = "https://deepsource.io/docs"
 bug_tracker = "https://bugtracker.deepsource.io"

[analysis]
 command = "/app/todo-checker"
