name = "todo comments checker"
shortcode = "@deepsource/demo-cli"
description = "finds the todo comments in codebase."
category = "doc"
tags = ["documentation","todo"]
environment_variables = {code_path = "/code"}

[urls]
 source = "https://github.com/deepsourcelabs/2do-checker"
 documentation = "https://deepsource.io/docs"
 bug_tracker = "https://bugtracker.deepsource.io"

[analysis]
 command = "/app/todo-checker"

[build]
 dockerfile = "Dockerfile"
